name: Second Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello World"
      - name: Print GoodBye
        run: echo "GoodBye"
      - name: Print Success
        run: echo "Success"
